feat: add french language to the locals
EwenDC/root-automated-setup pull request #10
Opened 2022-06-07 10:06 UTC by RomainStorai

*Checklist*: 

- [x] I have read the contribution guidelines. 
- [x] My pull request has a descriptive title
- [x] My pull request targets the main branch of freeCodeCamp.
- [x] I have tested these changes locally on my machine.

Translated auset-en.json to french in order to add the support of the French language.

```diff
+ Created auset-fr.json
```

Related to issue  #5

2022-06-08 06:25 UTC, EwenDC requested changes
Hi, thanks so much for submitting a translation. I am impressed by the speed at which you were able to produce it. There are a couple of issues to resolve before merging, but overall great work and thanks again for submitting!

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +    "marauderHirelings": "Pack de Mercenaires Maraudeurs",
![image](https://user-images.githubusercontent.com/39972488/172536165-9ff1c36e-75cf-4ff0-a3a6-2a2857e74404.png)
I am aware of the overflow issues caused by the long expansion names. I knew if there was a language that was going to challenge how much space I had left for text, it was going to be French 😋.

No action required from your side, I will fix the overflow issues before publishing the translation.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +    "noMap": "Aucune carte sélectionnée ! Veuillez sélectionner au moins une carte",
![image](https://user-images.githubusercontent.com/39972488/172536570-782fc26b-9761-4e84-a39f-5a6bdb603b8c.png)
Is having a space around both sides of the exclamation point intentional?

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i> 1. </i> Prenez le plateau de la carte Automne / Hiver dans la boîte de jeu et placez-le vers le bas avec la face Automne vers le haut. <br/> <i> 2. </i> Récupérez les 12 marqueurs
![image](https://user-images.githubusercontent.com/39972488/172537108-052b826b-e3ab-4c33-af1c-0a0fdb47aa93.png)
Please do not translate any text contained in diamond brackets (e.g. `<Bag/>`), the app uses this to display the icons for the vagabond items. You need to fix this in:
- faction.vagabond.setup
- faction.warlord.setup
- hireling.exile.setup_demoted
- landmark.forge.setup
- map.autumn.setup
- map.lake.setup
- map.mountain.setup
- map.winter.setup
- vagabond.arbiter.effect
- vagabond.harrier.effect
- vagabond.ranger.effect
- vagabond.ronin.effect
- vagabond.scoundrel.effect
- vagabond.thief.effect
- vagabond.tinker.effect
- vagabond.vagrant.effect

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i> 1. </i> Prenez le plateau de la carte Automne / Hiver dans la boîte de jeu et placez-le vers le bas avec la face Automne vers le haut. <br/> <i> 2. </i> Récupérez les 12 marqueurs
![image](https://user-images.githubusercontent.com/39972488/172538538-d08f1b20-cd55-4ebc-87b8-21e32c12d4a2.png)
Please remove the additional space added inside the closing `</i>` tag, This causes the whole line to render in italics instead of just the step number.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i>1.</i> Prenez le plateau de la carte Automne/Hiver dans la boîte de jeu et placez-le face hiver vers le haut.<br/><i>2.</i> Récupérez les 12 marqueurs de costume , retournez-les fa
![image](https://user-images.githubusercontent.com/39972488/172539025-dc66f8d9-fb3d-4cd3-8bf1-d407f1a66721.png)
Is the extra space around the comma intentional?

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i> 1. </i> Prenez le plateau de la carte Lac / Montagne dans la boîte de jeu et placez-le vers le bas avec le côté Lac vers le haut. <br/> <i> 2. </i> Récupérez les 12 marqueurs de c
![image](https://user-images.githubusercontent.com/39972488/172539312-d889c4b8-ef43-4e5d-a14b-7b56fbf3d62d.png)
Is the extra space before the full stop intentional?

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "landmarkSetup": "Placez la pièce Ferry dans la clairière d'angle qui est également une clairière côtière. Si vous avez une carte de repère \" The Ferry \", sortez-la de la boîte de jeu et plac
![image](https://user-images.githubusercontent.com/39972488/172539589-8d2cf4d4-5575-4dcb-be21-3cecce17c98b.png)
Is the card called "The Ferry" in the French language version of Root? I think whenever possible the French names of components should be used, as I would think that is most likely to be the version of the game the person using the app in French has.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "landmarkSetup": "Placez la pièce Tour dans la clairière centrale montrant deux tours. Si vous avez \" La Tour \"carte de repère, sortez-la de la boîte de jeu et placez-la à côté du plateau sur
![image](https://user-images.githubusercontent.com/39972488/172540249-3b0482c8-ae19-4688-b9a7-894a1358b53a.png)
Is the extra spaces around the quotes intentional?

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "Joueur {{count}}, placez le repère Ferry dans une clairière sur la rivière. Il ne peut pas avoir de point de repère ou être adjacent à un. Si vous avez une carte de repère\"Le Ferry\"
![image](https://user-images.githubusercontent.com/39972488/172541247-db826a6e-2f76-4b33-adbe-54e6a0ab64bd.png)
Is the extra space before the colon intentional?

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "Joueur {{count}}, placez le repère Ferry dans une clairière sur la rivière. Il ne peut pas avoir de point de repère ou être adjacent à un. Si vous avez une carte de repère\"Le Ferry\"
![image](https://user-images.githubusercontent.com/39972488/172541446-20ec6f38-29bf-42af-b982-a23e5819f975.png)
Is the lack of space between the quotes around "Le Ferry" and the previous word intentional?

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "summary": "<p>En tant que Gardiens de Fer, vous marquez des points en récupérant des <strong>reliques</strong> perdues lors de conflits passés. Vous devrez <strong>extraire</strong> des reliqu
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i>1.</i> Choisissez une clairière de patrie qui n'est pas adjacente aux patries ennemies.<br/><i>2.</i> Mettez 4 <strong>guerriers</strong> et 1 <strong>jardin</strong> correspondant
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i>1.</i> Choisissez une clairière de patrie qui n'est pas adjacente aux patries ennemies.<br/><i>2.</i> Mettez 2 <strong>guerriers</strong> et 1 <strong>tunnel</strong> dans votre pa
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i>1.</i> Choisissez une clairière de patrie sur la clairière du bord de la carte qui a 2+ clairières entre elle et les patries ennemies.<br/><i>2.</i> Mettez 6 <strong>guerriers< /st
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "summary": "<p>En tant que marquise de Cat, vous voulez transformer la forêt en une centrale industrielle et militaire. Chaque fois que vous placez un <strong>bâtiment</strong> sur la carte, vo
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i>1.</i> Choisissez 3 clairières de la patrie, chacune adjacente l'une à l'autre.<br/><i>2.</i> Placez 2 <strong>guerriers</strong> dans chacune de vos patries. Placez 1 <strong>guer
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "summary": "<p>En tant que Riverfolk Company, vous sillonnez les rivières serpentant à travers la grande forêt, offrant vos services à toute faction qui peut payer. Vous marquez des points de v
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "summary": "<p>En tant que Seigneur des Centaines, vous marquez des points lorsque vous <strong>opprimez</strong> vos ennemis. À la fin de votre tour, plus vous dirigez de clairières qui n'ont
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "summary": "<p>En tant qu'Alliance des Bois, vous travaillez pour gagner plus de sympathie envers les créatures forestières opprimées. Chaque fois que vous placez un <strong>jeton de sympathie<
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "setup": "<i>1.</i> Placez votre <strong>pion</strong> dans n'importe quelle forêt.<br/><i>2.</i> Mélangez le paquet de quêtes. Piochez 3 <strong>quêtes</strong> à distribuer à proximité.<br/><
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "summary": "<p>En tant que Culte des Lézards, vous vous occupez des créatures qui ont été rejetées par les autres factions. Vous marquez des points de victoire en effectuant les <strong>rituels
Please remove the extra spaces in the diamond tags, this is causing errors in the rendering of this text.

2022-06-08 06:25 UTC, EwenDC commented on public/locales/auset-fr.json
> +      "body": "La configuration est maintenant terminée. Le jeu commencera avec le Joueur {{count}}. Si vous souhaitez redémarrer le processus de configuration, utilisez le bouton ci-dessous.<p><i>\"
Feel free to add an extra line below my credit to credit yourself for the translation 🙂

e.g. ...`Developed By Ewen Cameron</i><br/><i>French translation by RomainStorai</i><br/><i>Based on the board game`...

2022-06-08 07:51 UTC, RomainStorai commented on public/locales/auset-fr.json
> +    "noMap": "Aucune carte sélectionnée ! Veuillez sélectionner au moins une carte",
Yes!

2022-06-08 07:55 UTC, RomainStorai commented on public/locales/auset-fr.json
> +      "landmarkSetup": "Placez la pièce Ferry dans la clairière d'angle qui est également une clairière côtière. Si vous avez une carte de repère \" The Ferry \", sortez-la de la boîte de jeu et plac
Okay, actually I wasn't sure about the french translation of the game (if the card keep the same name as some board game or if it is totally translated). I'm going to tranlate according to the real game.

2022-06-08 09:03 UTC, RomainStorai commented
I made the changes you requested. Hope it fits you well!

2022-06-09 04:59 UTC, merged

2022-06-09 04:59 UTC, EwenDC commented
Cheers!