Added telugu translations to the proj
EwenDC/root-automated-setup pull request #13
Opened 2022-06-11 13:34 UTC by moulibheemaneti

2022-06-21 12:27 UTC, EwenDC commented
Apologies, I started a new job so my free time to work on this project has diminished. I will try to review this in the coming days.

2022-06-22 03:59 UTC, moulibheemaneti commented
@EwenDC yeah sure.

2022-06-28 14:42 UTC, EwenDC requested changes
Hey, had some time to look at this. Please review the points I raised and make changes as appropriate. Thank you.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "setup": "<i>1.</i> గేమ్ బాక్స్ నుండి లేక్/మౌంటైన్ మ్యాప్ బోర్డ్‌ను పట్టుకుని, దానిని మౌంటైన్ వైపు పైకి కనిపించేలా ఉంచండి.<br/><i>2.</i> 6 క్లోజ్డ్ పాత్ మార్కర్‌లను ఉంచండి తవ్విన నేలతో ముదురు ర
`<i>4.</i> \"R\" <i>(మొత్తం నాలుగు)</i>తో గుర్తించబడిన మ్యాప్‌లోని ప్రతి స్లాట్‌లో ఒక శిధిలాన్ని ఉంచండి.`
Is there a Telegu localised version of Root? If so, how do they label ruin and starting items? If no local version then disregard.

`<i>5.< /i>`
Extra space within square brackets (<>) breaks HTML formatting

`2 <Boot/>, 2 <Bag/>, 1 <Crossbow/>, 1 <Hammer/>, 2 <Sword/> , 2 <టీ/>, 2 <కాయిన్/>.`
"Tea" and "Coin" tags have been incorrectly translated. Content within square brackets (<>) needs to remain in English so relevant formatting can occur. Also, there is an extra space after the sword icon.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "setup": "<i>1.</i> గేమ్ బాక్స్ నుండి శరదృతువు/శీతాకాలపు మ్యాప్ బోర్డ్‌ను పట్టుకుని, శరదృతువు వైపు పైకి కనిపించేలా ఉంచండి.<br/><i>2.</i> 12 సూట్ మార్కర్‌లను సేకరించండి, వాటిని క్రిందికి తిప్పి,
`<i>3.</i> \"Rతో గుర్తించబడిన మ్యాప్‌లోని ప్రతి స్లాట్‌లో ఒక శిధిలాన్ని ఉంచండి \" <i>(మొత్తం నాలుగు)</i>.`
The closing quote on the R has been chopped off ("R instead of "R")

`<i>4.</i> ఈ ఐటెమ్‌లను మ్యాప్ ఎగువన ఉన్న ఐటెమ్ సప్లై యొక్క మ్యాచింగ్ స్పేస్‌లలో ఉంచండి: 2 <Boot/ >, 2 <Bag/>, 1 <Crossbow/>, 1 <Hammer/>, 2 <Sword/>, 2 <Tea/>, 2 <Coin/>.<br/><i>5.</i > మ్యాప్ దగ్గర రెండు పాచికలను ఉంచండి.`
Extra space within square brackets (<>) breaks HTML formatting

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "setup": "{{count}}వ ఆటగాడు, లెజెండరీ ఫోర్జ్ ల్యాండ్‌మార్క్‌ను క్లియరింగ్‌లో ఉంచండి. ఇది మైలురాయిని కలిగి ఉండకూడదు లేదా ఒకదానికి ఆనుకొని ఉండకూడదు. గేమ్ బాక్స్ నుండి \"లెజెండరీ ఫోర్జ్\" ల్యాండ్‌
`<p><Mouse/>: < Bag/> <Bag/> <Tea/> <Tea/></p>`
Extra space within square brackets (<>) breaks HTML formatting

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "name": "బల్లి కల్ట్(లిజార్డ్ కల్ట్)",
I think the phonetic translation is a nice touch, however if the others are removed this should also be removed for consistency.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "name": "భూగర్భ ప్రదేశం(అండర్గ్రౌండ్ డచి)",
I think the phonetic translation is a nice touch, however it makes the faction name too long to fit neatly in the interface. I would suggest just using the faction name from the official Leder games translation, or if that doesn't exist use just the literal translation without the phonetic one.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "name": "ఐరీ రాజవంశాలు(ఐరీ డైనసైటిస్)",
I think the phonetic translation is a nice touch, however it makes the faction name too long to fit neatly in the interface. I would suggest just using the faction name from the official Leder games translation, or if that doesn't exist use just the literal translation without the phonetic one.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "name": "నూరేళ్ల స్వామి(లార్డ్ అఫ్ హుండ్రేడ్స్)",
I think the phonetic translation is a nice touch, however it makes the faction name too long to fit neatly in the interface. I would suggest just using the faction name from the official Leder games translation, or if that doesn't exist use just the literal translation without the phonetic one.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "name": "సంచారి(వాగాబాండ్)",
I think the phonetic translation is a nice touch, however it creates odd looking nested brackets when included in the faction select:
![image](https://user-images.githubusercontent.com/39972488/176201274-fda446ef-a08f-47b1-a4c0-872c09eedd1b.png)

and sometimes it even causes an overflow from being too long:
![image](https://user-images.githubusercontent.com/39972488/176201425-f1310ffd-7a11-4b0b-905e-b3ff7a87d9a8.png)

I would suggest just using the faction name from the official Leder games translation, or if that doesn't exist use just the literal translation without the phonetic one.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "name": "ఒకచోట నుండి మరియొక చోటికి మారు",
This vagabond name is simply too long to fit in the interface. I would advise against trying to perfectly capture the meaning of the word "vagrant" and instead opt for a nice single word that could describe someone who is a trouble maker. Conciseness is far more important than accuracy here, you just want a fun word that people might associate with how this vagabond plays.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "name": "లోహపు పాత్రలను బాగు చేయువాడు",
Ideally the vagabond name should just be a single word that could describe someone who creates. A literal translation of "tinker" is unnecessary and not required for the gameplay. Conciseness is far more important than accuracy here, you just want a fun word that people might associate with how this vagabond plays.

2022-06-28 14:42 UTC, EwenDC commented on public/locales/auset-te.json
> +      "body": "సెటప్ ఇప్పుడు పూర్తయింది. ప్లేయర్ {{count}}తో ఆట ప్రారంభమవుతుంది. మీరు సెటప్ ప్రాసెస్‌ను పునఃప్రారంభించాలనుకుంటే, దిగువ బటన్‌ను ఉపయోగించండి.<p><i>\"రూట్ ఆటోమేటెడ్ సెటప్\" ఎవెన్ కామెరాన
`<i>CC BY-NC-SA 4.0</i></p> కింద లైసెన్స్ పొందిన అప్లికేషన్`
The final line spills outside the paragraph. `</i></p>` should be _after_ the final piece of text

Also, feel free to add a credit for yourself here for work on the translation 😄. The translated line with the above fix and your credit (where it says "YOUR CREDIT HERE") should look like this:
`సెటప్ ఇప్పుడు పూర్తయింది. ప్లేయర్ {{count}}తో ఆట ప్రారంభమవుతుంది. మీరు సెటప్ ప్రాసెస్‌ను పునఃప్రారంభించాలనుకుంటే, దిగువ బటన్‌ను ఉపయోగించండి.<p><i>\"రూట్ ఆటోమేటెడ్ సెటప్\" ఎవెన్ కామెరాన్ ద్వారా డెవలప్ చేయబడింది</i><br/><i>YOUR CREDIT HERE</i><br/><i>బోర్డ్ గేమ్ ఆధారంగా \"రూట్ \" Leder Games ద్వారా ప్రచురించబడింది</i><br/><i>CC BY-NC-SA 4.0 కింద లైసెన్స్ పొందిన అప్లికేషన్</i></p>`

See the [French translation](https://github.com/EwenDC/root-automated-setup/blob/4d1e4ded732b7b5898b641c9d3fc6e4493687d50/public/locales/auset-fr.json#L125) for an example

2022-06-29 13:08 UTC, moulibheemaneti commented
Hi @EwenDC . I'll change the requested changes and I'll notify you.

2022-08-31 13:08 UTC, closed without merging